version: '3'

services:
  ioverlander:
    build: 
        context: ../
    ports:
     - "3000:3000"
    volumes:
     - ../../docker_dev_assets:/assets/
    # - ..:/app
    environment:
        DB_USERNAME: user
        DB_PASSWORD: password
        DB_HOSTNAME: postgres 
        NODE_ENV: staging
        BUILD_ASSETS_ON_LAUNCH: 1
        ASSETS_OUTPUT_PATH: "/assets/"
    depends_on:
     - postgres
  postgres:
    image: "postgres:9.6"
    volumes:
     - ../../docker_dev_pgdata:/pgdata
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        PGDATA: /pgdata
  staticassets:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ../../docker_dev_assets:/usr/share/nginx/html

